In [1]:
import pandas as pd

from sklearn.cross_validation import cross_val_score

/home/ian/anaconda3/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [2]:
df = pd.read_csv('/home/ian/Downloads/pima-indians-diabetes.csv', header=None)
df.head()

0    1   2   3    4     5      6   7  8
0  6  148  72  35    0  33.6  0.627  50  1
1  1   85  66  29    0  26.6  0.351  31  0
2  8  183  64   0    0  23.3  0.672  32  1
3  1   89  66  23   94  28.1  0.167  21  0
4  0  137  40  35  168  43.1  2.288  33  1

In [3]:
x=df.iloc[:,0:8]
x.head()

0    1   2   3    4     5      6   7
0  6  148  72  35    0  33.6  0.627  50
1  1   85  66  29    0  26.6  0.351  31
2  8  183  64   0    0  23.3  0.672  32
3  1   89  66  23   94  28.1  0.167  21
4  0  137  40  35  168  43.1  2.288  33

In [4]:
y=df.iloc[:,8]
y.head()

0    1
1    0
2    1
3    0
4    1
Name: 8, dtype: int64

In [5]:
from sklearn import metrics
from sklearn.model_selection import train_test_split

In [6]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

# 1_Logistic

In [7]:
from sklearn.linear_model import LogisticRegression

In [8]:
logit = LogisticRegression()

In [9]:
logit.fit(x_train,y_train)
logit.score(x_test,y_test)

0.7597402597402597

In [25]:
metrics.accuracy_score(y_test,logit.predict(x_test))

0.7597402597402597

# Logistic AUC

In [10]:
fpr, tpr, thresholds = metrics.roc_curve(
    y_test, logit.decision_function(x_test), pos_label=1)
metrics.auc(fpr, tpr)

0.8192837465564738

In [11]:
metrics.roc_auc_score( y_test, logit.decision_function(x_test))

0.8192837465564738

# Logistic Cross_Validation

In [22]:
cross_val_score(logit, x, y, cv=10).mean()

0.7669685577580314

# 2_SGD

In [23]:
from sklearn.linear_model import SGDClassifier
sgd = SGDClassifier(max_iter=10)
sgd.fit(x_train, y_train)
sgd.score(x_test, y_test)

0.6493506493506493

# SGD AUC

In [24]:
fpr, tpr, thresholds = metrics.roc_curve(
    y_test, sgd.decision_function(x_test), pos_label=1)
metrics.auc(fpr,tpr)

0.40697887970615243

In [25]:
metrics.roc_auc_score(y_test, sgd.decision_function(x_test))

0.40697887970615243

# SGD Cross_Validation

In [26]:
cross_val_score(sgd, x, y,cv=10).mean()

0.5218728639781272

# 3_SVM

In [13]:
from sklearn.svm import SVC

svc = SVC(kernel='linear')
svc.fit(x_train, y_train)
svc.score(x_test, y_test)

0.7532467532467533

In [9]:
from sklearn.svm import SVC

svc = SVC(kernel='rbf')
svc.fit(x_train, y_train)
svc.score(x_test, y_test)

0.6428571428571429

In [10]:
#from sklearn.svm import SVC

#svc = SVC(kernel='poly')
#svc.fit(x_train, y_train)
#svc.score(x_test, y_test)

In [11]:
from sklearn.svm import SVC

svc = SVC(kernel='sigmoid')
svc.fit(x_train, y_train)
svc.score(x_test, y_test)

0.6428571428571429

# SVM AUC

In [14]:
fpr, tpr, thresholds = metrics.roc_curve(
    y_test, svc.decision_function(x_test), pos_label=1)
metrics.auc(fpr,tpr)

0.8165289256198347

In [15]:
metrics.roc_auc_score(y_test, svc.decision_function(x_test))

0.8165289256198347

# SVM Cross_Validation

In [18]:
cross_val_score(svc,x,y,scoring='accuracy',cv=10).mean()

0.7669685577580314

# Perceptron

In [19]:
from sklearn.linear_model import Perceptron

perc=Perceptron(max_iter=10)
perc.fit(x_train, y_train)
perc.score(x_test, y_test)

0.6493506493506493

# Perceptron AUC

In [21]:
fpr, tpr, thresholds = metrics.roc_curve(
    y_test, perc.decision_function(x_test), pos_label=1)
metrics.auc(fpr,tpr)

0.45179063360881544

In [22]:
metrics.roc_auc_score(y_test, perc.decision_function(x_test))

0.45179063360881544

# Perceptron Cross_validation

In [23]:
cross_val_score(perc,x,y,scoring='accuracy',cv=10).mean()

0.644583048530417

# Random Forest Classifer

In [29]:
from sklearn.ensemble import  RandomForestClassifier

rf = RandomForestClassifier()
rf = rf.fit(x_train,y_train)
rf.score(x_test,y_test)

0.7272727272727273

In [30]:
cross_val_score(rf,x,y).mean()

0.7383346764451565

In [31]:
metrics.accuracy_score(y_test,rf.predict(x_test))

0.7272727272727273

In [32]:
metrics.roc_auc_score(y_test,rf.predict(x_test))

0.6909090909090908

In [24]:
#pd.Series(y).value_counts()

In [46]:
fpr, tpr, thresholds = metrics.roc_curve(
    y_test, rf.predict(x_test), pos_label=1)
metrics.auc(fpr,tpr)

0.6909090909090908

# ExtraTreesClassifier

In [35]:
from sklearn.ensemble import ExtraTreesClassifier

etc = RandomForestClassifier()
etc = etc.fit(x_train,y_train)
etc.score(x_test,y_test)

0.7402597402597403

In [20]:
cross_val_score(etc,x,y).mean()

0.7422001959830625

In [21]:
etc.feature_importances_

array([0.08099847, 0.24683493, 0.08681247, 0.07261485, 0.08579845,
       0.17741444, 0.14105613, 0.10847025])

In [36]:
metrics.accuracy_score(y_test,etc.predict(x_test))

0.7402597402597403

In [37]:
metrics.roc_auc_score(y_test,etc.predict(x_test))

0.6929292929292928

In [47]:
fpr, tpr, thresholds = metrics.roc_curve(
    y_test, etc.predict(x_test), pos_label=1)
metrics.auc(fpr,tpr)

0.6929292929292928

# Adaboost Classifier

In [26]:
from sklearn.ensemble import AdaBoostClassifier

adb = AdaBoostClassifier()
adb = etc.fit(x_train,y_train)
adb.score(x_test,y_test)

0.7597402597402597

In [51]:
cross_val_score(adb,x,y).mean()

0.7604802657930877

In [27]:
metrics.accuracy_score(y_test,adb.predict(x_test))

0.7597402597402597

In [28]:
metrics.roc_auc_score(y_test,adb.predict(x_test))

0.7202020202020201

In [48]:
fpr, tpr, thresholds = metrics.roc_curve(
    y_test, adb.predict(x_test), pos_label=1)
metrics.auc(fpr,tpr)

0.7202020202020201

# Gradient Boosting Classifier

In [49]:
from sklearn.ensemble import GradientBoostingClassifier

gbc = GradientBoostingClassifier()
gbc = gbc.fit(x_train,y_train)
gbc.score(x_test,y_test)

0.7467532467532467

In [52]:
metrics.accuracy_score(y_test,gbc.predict(x_test))

0.7467532467532467

In [50]:
metrics.roc_auc_score(y_test,gbc.decision_function(x_test))

0.8089990817263545

In [51]:
fpr, tpr, thresholds = metrics.roc_curve(
    y_test, gbc.decision_function(x_test), pos_label=1)
metrics.auc(fpr,tpr)

0.8089990817263545

In [68]:
gbc.feature_importances_

array([0.06656664, 0.20749767, 0.09512673, 0.05169821, 0.06687878,
       0.15744395, 0.21458714, 0.14020089])

# Gradient Boosting Regressor

In [59]:
from sklearn.ensemble import GradientBoostingRegressor

gbr = GradientBoostingRegressor()
gbr = gbr.fit(x_train,y_train)
gbr.score(x_test,y_test)

0.25660920115747254

# Majority Class Labels (Majority/Hard Voting)

In [1]:
from sklearn import datasets
from sklearn.cross_validation import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import VotingClassifier

/home/ian/anaconda3/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [2]:
iris = datasets.load_iris()
x,y = iris.data[:,1:3],iris.target

In [3]:
clf1 = LogisticRegression(random_state=1)
clf2 = RandomForestClassifier(random_state=1)
clf3 = GaussianNB()

In [4]:
eclf = VotingClassifier(
    estimators=[('lr', clf1), ('rf', clf2), ('gnb', clf3)], voting='hard')

In [5]:
for clf, label in zip([clf1, clf2, clf3, eclf], ['Logistic Regression', 'Random Forest', 'naive Bayes', 'Ensemble']):
    scores = cross_val_score(clf, x, y, cv=5, scoring='accuracy')
    print("Accuracy: %0.2f (+/- %0.2f) [%s]" %
          (scores.mean(), scores.std(), label))

Accuracy: 0.90 (+/- 0.05) [Logistic Regression]
Accuracy: 0.93 (+/- 0.05) [Random Forest]
Accuracy: 0.91 (+/- 0.04) [naive Bayes]
Accuracy: 0.95 (+/- 0.05) [Ensemble]


/home/ian/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
/home/ian/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
/home/ian/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
/home/ian/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Re

In [ ]:
eclf.predict

In [6]:
from sklearn import datasets
from sklearn.cross_validation import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import VotingClassifier

clf1 = LogisticRegression(random_state=1)
clf2 = RandomForestClassifier(random_state=1)
clf3 = GaussianNB()

eclf = VotingClassifier(
    estimators=[('lr', clf1), ('rf', clf2), ('gnb', clf3)], voting='hard')

for clf, label in zip([clf1, clf2, clf3, eclf], ['Logistic Regression', 'Random Forest', 'naive Bayes', 'Ensemble']):
    scores = cross_val_score(clf, x, y, cv=5, scoring='accuracy')
    print("Accuracy: %0.2f (+/- %0.2f) [%s]" %
          (scores.mean(), scores.std(), label))

Accuracy: 0.90 (+/- 0.05) [Logistic Regression]
Accuracy: 0.93 (+/- 0.05) [Random Forest]
Accuracy: 0.91 (+/- 0.04) [naive Bayes]
Accuracy: 0.95 (+/- 0.05) [Ensemble]


/home/ian/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
/home/ian/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
/home/ian/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
/home/ian/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Re

## clf1

In [136]:
clf1.fit(x,y);clf2.fit(x,y);clf3.fit(x,y);eclf.fit(x,y)

VotingClassifier(estimators=[('lr', LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=1, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)), ('rf', RandomFore...   oob_score=False, random_state=1, verbose=0, warm_start=False)), ('gnb', GaussianNB(priors=None))],
         flatten_transform=None, n_jobs=1, voting='hard', weights=None)

In [139]:
metrics.confusion_matrix(y,clf1.predict(x))

array([[50,  0,  0],
       [ 0, 39, 11],
       [ 0,  0, 50]])

In [140]:
(50+39+50)/(11+50+39+50)

0.9266666666666666

In [141]:
clf1.score(x,y)

0.9266666666666666

In [144]:
(pd.Series(clf1.predict(x) == y)).value_counts()

True     139
False     11
dtype: int64

In [145]:
139/150

0.9266666666666666

## clf2

In [146]:
metrics.confusion_matrix(y,clf2.predict(x))

array([[50,  0,  0],
       [ 0, 48,  2],
       [ 0,  0, 50]])

In [147]:
(50+48+50)/(2+50+48+50)

0.9866666666666667

In [148]:
clf2.score(x,y)

0.9866666666666667

In [149]:
(pd.Series(clf2.predict(x) == y)).value_counts()

True     148
False      2
dtype: int64

In [150]:
148/150

0.9866666666666667

## clf3

In [151]:
metrics.confusion_matrix(y,clf3.predict(x))

array([[50,  0,  0],
       [ 0, 46,  4],
       [ 0,  8, 42]])

In [152]:
(50+46+42)/(4+8+50+46+42)

0.92

In [153]:
clf3.score(x,y)

0.92

In [154]:
(pd.Series(clf3.predict(x) == y)).value_counts()

True     138
False     12
dtype: int64

In [155]:
138/(138+12)

0.92

## eclf

In [156]:
metrics.confusion_matrix(y,eclf.predict(x))

/home/ian/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


array([[50,  0,  0],
       [ 0, 46,  4],
       [ 0,  0, 50]])

In [157]:
(50+46+50)/(4+50+46+50)

0.9733333333333334

In [158]:
eclf.score(x,y)

/home/ian/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


0.9733333333333334

In [159]:
(pd.Series(eclf.predict(x) == y)).value_counts()

/home/ian/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


True     146
False      4
dtype: int64

In [160]:
146/(146+4)

0.9733333333333334

# Weighted Average Probabilities (Soft Voting)

In [12]:
from sklearn import datasets
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from itertools import product
from sklearn.ensemble import VotingClassifier

# Loading some example data
iris = datasets.load_iris()
X = iris.data[:, [0,2]]
y = iris.target

# Training classifiers
clf1 = DecisionTreeClassifier(max_depth=4)
clf2 = KNeighborsClassifier(n_neighbors=7)
clf3 = SVC(kernel='rbf', probability=True)
eclf = VotingClassifier(estimators=[('dt', clf1), ('knn', clf2), ('svc', clf3)], voting='soft', weights=[2,1,2])

clf1 = clf1.fit(X,y)
clf2 = clf2.fit(X,y)
clf3 = clf3.fit(X,y)
eclf = eclf.fit(X,y)

In [13]:
cross_val_score(clf1, X, y, cv=5, scoring='accuracy').mean()

0.9266666666666667

In [14]:
cross_val_score(clf2, X, y, cv=5, scoring='accuracy').mean()

0.9400000000000001

In [15]:
cross_val_score(clf3, X, y, cv=5, scoring='accuracy').mean()

0.9466666666666667

In [16]:
cross_val_score(eclf, X, y, cv=5, scoring='accuracy').mean()

/home/ian/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
/home/ian/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
/home/ian/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
/home/ian/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Re

0.9466666666666667

## example

In [17]:
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier, VotingClassifier

clf1 = LogisticRegression(random_state=1)
clf2 = RandomForestClassifier(random_state=1)
clf3 = GaussianNB()

X = np.array([[-1, -1], [-2, -1], [-3, -2], [1, 1], [2, 1], [3, 2]])
y = np.array([1, 1, 1, 2, 2, 2])

eclf1 = VotingClassifier(estimators=[
    ('lr', clf1), ('rf', clf2), ('gnb', clf3)], voting='hard')
eclf1 = eclf1.fit(X, y)

In [18]:
print(eclf1.predict(X))

[1 1 1 2 2 2]


/home/ian/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


In [19]:
eclf2 = VotingClassifier(
    estimators=[('lr', clf1), ('rf', clf2), ('gnb', clf3)], voting='soft')
eclf2 = eclf2.fit(X, y)
print(eclf2.predict(X))

[1 1 1 2 2 2]


/home/ian/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


In [20]:
eclf3 = VotingClassifier(estimators=[('lr', clf1), ('rf', clf2), (
    'gnb', clf3)], voting='soft', weights=[2, 1, 1], flatten_transform=True)
eclf3 = eclf3.fit(X, y)
print(eclf3.predict(X))

[1 1 1 2 2 2]


/home/ian/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


In [167]:
print(eclf3.transform(X).shape)

(6, 6)


# Using the VotingClassifier with GridSearch

In [171]:
from sklearn.model_selection import GridSearchCV

clf1 = LogisticRegression(random_state=1)
clf2 = RandomForestClassifier(random_state=1)
clf3 = GaussianNB()
eclf = VotingClassifier(
    estimators=[('lr', clf1), ('rf', clf2), ('gnb', clf3)], voting='soft')

params = {'lr__C': [1.0, 100.0], 'rf__n_estimators': [20, 200], }

grid = GridSearchCV(estimator=eclf, param_grid=params, cv=5)
grid = grid.fit(iris.data, iris.target)

/home/ian/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
/home/ian/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
/home/ian/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
/home/ian/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Re

/home/ian/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
/home/ian/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
/home/ian/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
/home/ian/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Re

In [172]:
grid.score(iris.data,iris.target)

/home/ian/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


0.9733333333333334

# xgboost

In [ ]:
import xgboost as xgb

In [ ]:
dtrain = xgb.DMatrix(x_train,label=y_train)

In [ ]:
dtest = xgb.DMatrix(x_test)

In [ ]:
params = {'booster': 'gbtree',
          'objective': 'binary:logistic',
          'eval_metric':'auc',
          'max_depth': 4,
          'lambda': 10,
          'subsample': 0.75,
          'colsample_bytree': 0.75,
          'min_child_weight': 2,
          'eta': 0.025,
          'seed': 0,
          'silent': 0}

In [ ]:
watchlist = [(dtrain, 'train')]

In [ ]:
bst = xgb.train(params,dtrain, num_boost_round=200, evals=watchlist)#+early_stopping_rounds=100

In [ ]:
ypred = bst.predict(dtest)

In [ ]:
y_pred = (ypred >= 0.5)*1

In [ ]:
from sklearn import metrics
metrics.precision_score(y_test, y_pred)

In [ ]:
metrics.confusion_matrix(y_test,y_pred)

In [ ]:
metrics.roc_auc_score(y_test,ypred)

In [ ]:
(y_test == y_pred).value_counts()

In [ ]:
115/(115+39)

In [ ]:
115+39

In [ ]:
fpr, tpr, thresholds = metrics.roc_curve(
    y_test, ypred, pos_label=1)

In [ ]:
metrics.auc(fpr,tpr)

In [ ]:
clf.predict_proba(x_test)